name: Software manifest

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 2pm UTC
    - cron: '00 13 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
