name: 'Run tests'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm run all
        run: |
          npm install
          npm run all
